#!/usr/bin/env python3
"""Hermetic tests for the `relink` verb in agents/objectives.py.

No network, no live vault. Builds a temp fixture with one of each node type,
runs relink --apply, and asserts correctness.

Run: .venv/bin/python -m pytest tests/test_objectives_relink.py -q
"""

from __future__ import annotations

import importlib.util
import os
import re
import sys
import tempfile
from pathlib import Path

REPO = Path(os.environ.get("CODE_PATH", "/home/jpietrak/second_brain"))
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))


def _load(modname: str, relpath: str):
    spec = importlib.util.spec_from_file_location(modname, REPO / relpath)
    mod = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(mod)
    return mod


objectives = _load("objectives", "agents/objectives.py")
obj_init = _load("obj_init", "scripts/obj_init.py")


# ---------------------------------------------------------------------------
# Fixture builders
# ---------------------------------------------------------------------------

def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def make_relink_fixture(vault: Path) -> None:
    """Create one node of each relevant type for relink testing.

    Uses plain-id frontmatter fields exactly as the live vault does.
    Does NOT pre-populate aliases or written_by (relink must NOT add aliases).
    """
    obj_init.run_apply(vault)

    # -- purpose --
    _write(vault / "objective/purpose/PURPOSE.md", """\
---
type: purpose
id: purpose
created: 2026-06-21
updated: 2026-06-21
status: active
vault: TestVault
---

## For future Claude
This is the vault PURPOSE file.

# Vault purpose

## Mission
Test vault for relink tests.
""")

    # -- topic -- related_questions as inline YAML list
    _write(vault / "objective/topic/T-0001-test-topic.md", """\
---
type: topic
id: T-0001
created: 2026-06-21
updated: 2026-06-21
status: active
related_questions: [Q-0001, Q-0002]
---

## For future Claude
This is a TOPIC node.

# Topic: Test topic

## Summary
A test topic node.
""")

    # -- research_question -- primary topic + secondary topic in body preamble
    _write(vault / "objective/research_question/Q-0001-test-rq.md", """\
---
type: research_question
id: Q-0001
created: 2026-06-21
updated: 2026-06-21
solved: "no"
topic: T-0001
priority: high
answer_ref: ""
---

## For future Claude
This is a RESEARCH QUESTION node.
Secondary topic: T-0002 (optical accelerators).

# Research question

What is the test latency floor?
""")

    # -- direction -- topics as comma-separated string (live vault format)
    _write(vault / "objective/direction/DIR-0001-test-dir.md", """\
---
type: direction
id: DIR-0001
created: 2026-06-22
updated: 2026-06-22
generated_by: research
serves_question: Q-0001
topics: T-0001, T-0002
targets_gap: "test gap"
priority: high
status: open
---

## For future Claude
This direction was generated by obj-synth.

## reasoning_pattern
Test reasoning.

## expected_evidence
Test evidence.

## seed_queries
Test queries.

## solves_when
Test condition.
""")

    # -- research_question_proposal -- from_gap contains Q and T ids
    _write(vault / "objective/research_question_proposal/QP-0001-test-prop.md", """\
---
type: research_question_proposal
id: QP-0001
created: 2026-06-22
updated: 2026-06-22
generated_by: research
from_gap: Cross-cutting gap involving Q-0001 and Q-0002; also relevant to T-0003
status: pending
---

## For future Claude
This proposal was generated by obj-synth.

## Proposed question
What test question should we ask?

## Rationale
Related to Q-0001 and T-0001 work in the vault.
""")

    # -- decision -- scope=all -> links PURPOSE
    _write(vault / "objective/decision/D-0001-test-decision.md", """\
---
type: decision
id: D-0001
created: 2026-06-21
updated: 2026-06-21
status: active
scope: all
---

## For future Claude
This is a DECISION node.

# Decision

Do not fetch web content.
""")

    # -- decision with node-id scope -- scope=Q-0001
    _write(vault / "objective/decision/D-0002-scoped-decision.md", """\
---
type: decision
id: D-0002
created: 2026-06-21
updated: 2026-06-21
status: active
scope: Q-0001
---

## For future Claude
This decision governs Q-0001 specifically.

# Decision

Scoped decision content.
""")


# ---------------------------------------------------------------------------
# Helper: read frontmatter + body
# ---------------------------------------------------------------------------

_FM_RE = re.compile(r"^---\n(.*?)\n---(?:\n|$)", re.DOTALL)


def _read_fm(path: Path) -> dict[str, str]:
    return objectives._parse_fm(path.read_text(encoding="utf-8"))


def _read_body(path: Path) -> str:
    return objectives._body(path.read_text(encoding="utf-8"))


def _read_inline_list(raw: str) -> list[str]:
    return objectives._parse_inline_list(raw)


# ---------------------------------------------------------------------------
# Test: dry-run reports changes without writing
# ---------------------------------------------------------------------------

def test_relink_dryrun_no_writes() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        # Capture mtimes before.
        topic_path = vault / "objective/topic/T-0001-test-topic.md"
        mtime_before = topic_path.stat().st_mtime

        results = objectives.relink(vault, apply=False)
        assert results, "relink returned empty results"

        # File must NOT be written in dry-run.
        mtime_after = topic_path.stat().st_mtime
        assert mtime_before == mtime_after, "dry-run must not write files"

        # But results should show changes planned.
        topic_result = next(
            (r for r in results if "T-0001" in r["path"]), None
        )
        assert topic_result is not None, "no result for T-0001"
        assert topic_result["changed"], "T-0001 should report planned change"

    print("PASS test_relink_dryrun_no_writes")


# ---------------------------------------------------------------------------
# Test (a): relink does NOT add aliases to nodes that had none
# ---------------------------------------------------------------------------

def test_relink_no_aliases_added() -> None:
    """relink must NOT add an aliases key to nodes that did not already have one."""
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        objectives.relink(vault, apply=True)

        for rel_path in (
            "objective/purpose/PURPOSE.md",
            "objective/topic/T-0001-test-topic.md",
            "objective/research_question/Q-0001-test-rq.md",
            "objective/direction/DIR-0001-test-dir.md",
            "objective/research_question_proposal/QP-0001-test-prop.md",
            "objective/decision/D-0001-test-decision.md",
        ):
            fm = _read_fm(vault / rel_path)
            assert "aliases" not in fm, (
                f"{rel_path}: relink must NOT add an aliases key, but got {fm.get('aliases')!r}"
            )

    print("PASS test_relink_no_aliases_added")


# ---------------------------------------------------------------------------
# Test (a2): node that starts with aliases:[<id>] has own-id alias removed
# ---------------------------------------------------------------------------

def test_relink_own_id_alias_removed() -> None:
    """A node whose aliases list contains exactly its own id has that entry removed.

    If the list becomes empty after removal, the aliases key is dropped entirely.
    Any OTHER pre-existing aliases are preserved.
    """
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        obj_init.run_apply(vault)

        # Case 1: aliases = [T-0001] only -> key should be removed entirely.
        _write(vault / "objective/topic/T-0001-only-self-alias.md", """\
---
type: topic
id: T-0001
created: 2026-06-21
updated: 2026-06-21
status: active
aliases: [T-0001]
related_questions: []
---

## For future Claude
Node with only own-id alias.

# Topic: Self-alias only
""")

        # Case 2: aliases = [T-0002, some-other-alias] -> T-0002 removed, other preserved.
        _write(vault / "objective/topic/T-0002-mixed-aliases.md", """\
---
type: topic
id: T-0002
created: 2026-06-21
updated: 2026-06-21
status: active
aliases: [T-0002, some-other-alias]
related_questions: []
---

## For future Claude
Node with mixed aliases.

# Topic: Mixed aliases
""")

        # Case 3: aliases = [some-other-alias] (no own id) -> completely unchanged.
        _write(vault / "objective/topic/T-0003-no-self-alias.md", """\
---
type: topic
id: T-0003
created: 2026-06-21
updated: 2026-06-21
status: active
aliases: [some-other-alias]
related_questions: []
---

## For future Claude
Node with no own-id alias.

# Topic: No self alias
""")

        objectives.relink(vault, apply=True)

        # Case 1: aliases key must be gone.
        fm1 = _read_fm(vault / "objective/topic/T-0001-only-self-alias.md")
        assert "aliases" not in fm1, (
            f"T-0001: aliases key should be removed when only own-id was present, "
            f"got {fm1.get('aliases')!r}"
        )

        # Case 2: T-0002 removed; some-other-alias preserved.
        fm2 = _read_fm(vault / "objective/topic/T-0002-mixed-aliases.md")
        aliases2 = _read_inline_list(fm2.get("aliases", ""))
        assert "T-0002" not in aliases2, (
            f"T-0002: own-id alias should be removed, aliases={aliases2}"
        )
        assert "some-other-alias" in aliases2, (
            f"T-0002: other alias 'some-other-alias' must be preserved, aliases={aliases2}"
        )

        # Case 3: aliases key unchanged (no own-id to remove).
        fm3 = _read_fm(vault / "objective/topic/T-0003-no-self-alias.md")
        aliases3 = _read_inline_list(fm3.get("aliases", ""))
        assert "some-other-alias" in aliases3, (
            f"T-0003: 'some-other-alias' must be preserved unchanged, aliases={aliases3}"
        )

    print("PASS test_relink_own_id_alias_removed")


# ---------------------------------------------------------------------------
# Test (b): written_by set correctly per type; generated_by is REMOVED
# ---------------------------------------------------------------------------

def test_relink_generated_by_removal() -> None:
    """Existing nodes with generated_by but no written_by must be migrated:
    1. written_by is set to the generated_by value (per type)
    2. generated_by is REMOVED from frontmatter (no code reads it anymore)
    3. rerun is idempotent (no further changes)
    """
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        obj_init.run_apply(vault)

        # Create a direction node with ONLY generated_by, no written_by.
        _write(vault / "objective/direction/DIR-0001-test-migration.md", """\
---
type: direction
id: DIR-0001
created: 2026-06-22
updated: 2026-06-22
generated_by: research
serves_question: Q-0001
topics: T-0001
priority: high
status: open
---

## For future Claude
This direction was generated by obj-synth.

## reasoning_pattern
Test reasoning.
""")

        # First relink: should set written_by=research and REMOVE generated_by.
        results1 = objectives.relink(vault, apply=True)
        dir_record = next((r for r in results1 if "DIR-0001" in r["path"]), None)
        assert dir_record is not None, "DIR-0001 record missing"
        assert dir_record["changed"], "first relink should report change for DIR-0001"
        assert dir_record["generated_by_removed"], (
            "first relink should report generated_by_removed=True"
        )

        # Check the file after first relink.
        fm1 = _read_fm(vault / "objective/direction/DIR-0001-test-migration.md")
        assert fm1.get("written_by") == "research", (
            f"DIR-0001: written_by should be 'research' after migration, got {fm1.get('written_by')!r}"
        )
        assert "generated_by" not in fm1, (
            f"DIR-0001: generated_by should have been REMOVED, but still present: {fm1.get('generated_by')!r}"
        )

        # Second relink: must be idempotent (no further changes).
        results2 = objectives.relink(vault, apply=True)
        dir_record2 = next((r for r in results2 if "DIR-0001" in r["path"]), None)
        assert dir_record2 is not None, "DIR-0001 record missing on second run"
        assert not dir_record2["changed"], (
            f"second relink must be idempotent; DIR-0001 should not change, but changed={dir_record2['changed']}"
        )

        # Verify file content is identical.
        fm2 = _read_fm(vault / "objective/direction/DIR-0001-test-migration.md")
        assert fm2.get("written_by") == "research", (
            "DIR-0001: written_by must remain 'research' on second run"
        )
        assert "generated_by" not in fm2, (
            "DIR-0001: generated_by must still be absent on second run"
        )

    print("PASS test_relink_generated_by_removal")


def test_relink_written_by_per_type() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        objectives.relink(vault, apply=True)

        # USER types.
        for path, node_id in [
            (vault / "objective/purpose/PURPOSE.md", "purpose"),
            (vault / "objective/topic/T-0001-test-topic.md", "T-0001"),
            (vault / "objective/research_question/Q-0001-test-rq.md", "Q-0001"),
            (vault / "objective/decision/D-0001-test-decision.md", "D-0001"),
        ]:
            fm = _read_fm(path)
            assert fm.get("written_by") == "USER", (
                f"{node_id}: expected written_by=USER, got {fm.get('written_by')!r}"
            )

        # Agent-authored types: direction has generated_by=research -> written_by=research.
        dir_fm = _read_fm(vault / "objective/direction/DIR-0001-test-dir.md")
        assert dir_fm.get("written_by") == "research", (
            f"DIR-0001 written_by: expected 'research', got {dir_fm.get('written_by')!r}"
        )
        # generated_by must be REMOVED (write-side no longer emits it; safe to drop).
        assert "generated_by" not in dir_fm, (
            f"DIR-0001 generated_by should have been removed, still present: {dir_fm.get('generated_by')!r}"
        )

        # Proposal has generated_by=research -> written_by=research.
        qp_fm = _read_fm(vault / "objective/research_question_proposal/QP-0001-test-prop.md")
        assert qp_fm.get("written_by") == "research", (
            f"QP-0001 written_by: expected 'research', got {qp_fm.get('written_by')!r}"
        )
        assert "generated_by" not in qp_fm, (
            "QP-0001 generated_by should have been removed"
        )

    print("PASS test_relink_written_by_per_type")


# ---------------------------------------------------------------------------
# Test (b2): agent_todo with no generated_by gets written_by=research
# ---------------------------------------------------------------------------

def test_relink_written_by_agent_todo_default() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        obj_init.run_apply(vault)

        _write(vault / "objective/agent_todo/TODO-0001-test.md", """\
---
type: agent_todo
id: TODO-0001
created: 2026-06-22
updated: 2026-06-22
status: open
---

## For future Claude
Test todo.

# Todo

Do something.
""")

        objectives.relink(vault, apply=True)

        todo_fm = _read_fm(vault / "objective/agent_todo/TODO-0001-test.md")
        assert todo_fm.get("written_by") == "research", (
            f"TODO-0001 without generated_by should default to 'research', "
            f"got {todo_fm.get('written_by')!r}"
        )

    print("PASS test_relink_written_by_agent_todo_default")


# ---------------------------------------------------------------------------
# Test (c): ## Links section contains FULL path-qualified wikilinks
# ---------------------------------------------------------------------------

def test_relink_links_section_full_paths() -> None:
    """The ## Links block must use full path-qualified wikilinks, not bare ids."""
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        objectives.relink(vault, apply=True)

        # purpose: NO ## Links section.
        purpose_body = _read_body(vault / "objective/purpose/PURPOSE.md")
        assert "<!-- links:auto -->" not in purpose_body, (
            "purpose must NOT get a Links section"
        )

        # topic: part of PURPOSE (full path) + question links (full paths).
        topic_body = _read_body(vault / "objective/topic/T-0001-test-topic.md")
        assert "[[objective/purpose/PURPOSE]]" in topic_body, (
            "topic: missing full-path [[objective/purpose/PURPOSE]] link"
        )
        # bare [[PURPOSE]] must NOT appear (it must be the full path)
        assert "[[PURPOSE]]" not in topic_body, (
            "topic: bare [[PURPOSE]] must not appear; use full path"
        )
        # Q-0001 full path present
        assert "[[objective/research_question/Q-0001-test-rq]]" in topic_body, (
            "topic: missing full-path [[objective/research_question/Q-0001-test-rq]] link"
        )
        # bare [[Q-0001]] must not appear
        assert "[[Q-0001]]" not in topic_body, (
            "topic: bare [[Q-0001]] must not appear; use full path"
        )
        # Q-0002 is dangling (no fixture file) -> fallback bare [[Q-0002]] is acceptable
        assert "Q-0002" in topic_body, "topic: Q-0002 reference missing entirely"

        # research_question: primary topic + secondary topic with full paths.
        rq_body = _read_body(vault / "objective/research_question/Q-0001-test-rq.md")
        assert "[[objective/topic/T-0001-test-topic]]" in rq_body, (
            "rq: missing full-path [[objective/topic/T-0001-test-topic]] for primary topic"
        )
        assert "[[T-0001]]" not in rq_body, (
            "rq: bare [[T-0001]] must not appear; use full path"
        )
        # T-0002 is dangling -> fallback bare [[T-0002]]
        assert "T-0002" in rq_body, "rq: T-0002 secondary topic reference missing"

        # direction: serves Q-0001, topics T-0001 + T-0002.
        dir_body = _read_body(vault / "objective/direction/DIR-0001-test-dir.md")
        assert "[[objective/research_question/Q-0001-test-rq]]" in dir_body, (
            "direction: missing full-path serves link for Q-0001"
        )
        assert "[[Q-0001]]" not in dir_body, (
            "direction: bare [[Q-0001]] must not appear; use full path"
        )
        assert "[[objective/topic/T-0001-test-topic]]" in dir_body, (
            "direction: missing full-path [[objective/topic/T-0001-test-topic]]"
        )
        assert "[[T-0001]]" not in dir_body, (
            "direction: bare [[T-0001]] must not appear; use full path"
        )
        # T-0002 dangling -> fallback bare [[T-0002]]
        assert "T-0002" in dir_body, "direction: T-0002 topic reference missing"
        assert "- serves:" in dir_body, "direction: missing 'serves' relation label"
        assert "- topic:" in dir_body, "direction: missing 'topic' relation label"

        # research_question_proposal: ids from from_gap + body
        qp_body = _read_body(vault / "objective/research_question_proposal/QP-0001-test-prop.md")
        # Q-0001 has a fixture file -> full path
        assert "[[objective/research_question/Q-0001-test-rq]]" in qp_body, (
            "QP-0001: missing full-path Q-0001 link"
        )
        # Q-0002 dangling -> fallback bare
        assert "Q-0002" in qp_body, "QP-0001: Q-0002 reference missing"
        # T-0003 dangling -> fallback bare [[T-0003]]
        assert "T-0003" in qp_body, "QP-0001: missing T-0003 from from_gap"
        # T-0001 from body -> full path
        assert "[[objective/topic/T-0001-test-topic]]" in qp_body, (
            "QP-0001: missing full-path T-0001 link from body"
        )

        # decision scope=all -> governs PURPOSE full path.
        d_body = _read_body(vault / "objective/decision/D-0001-test-decision.md")
        assert "[[objective/purpose/PURPOSE]]" in d_body, (
            "D-0001: missing full-path [[objective/purpose/PURPOSE]] governs link"
        )
        assert "[[PURPOSE]]" not in d_body, (
            "D-0001: bare [[PURPOSE]] must not appear; use full path"
        )
        assert "- governs:" in d_body, "D-0001: missing 'governs' relation"

        # decision scope=Q-0001 -> governs Q-0001 full path.
        d2_body = _read_body(vault / "objective/decision/D-0002-scoped-decision.md")
        assert "[[objective/research_question/Q-0001-test-rq]]" in d2_body, (
            "D-0002: missing full-path governs link for Q-0001"
        )
        assert "[[PURPOSE]]" not in d2_body, (
            "D-0002 scope=Q-0001 must NOT link PURPOSE"
        )
        assert "[[objective/purpose/PURPOSE]]" not in d2_body, (
            "D-0002 scope=Q-0001 must NOT link PURPOSE (full path either)"
        )

    print("PASS test_relink_links_section_full_paths")


# ---------------------------------------------------------------------------
# Test (d): idempotency -- second run writes nothing
# ---------------------------------------------------------------------------

def test_relink_idempotent() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        # First apply.
        results1 = objectives.relink(vault, apply=True)
        changed1 = [r for r in results1 if r["changed"]]
        assert changed1, "first relink should change at least some files"

        # Snapshot content after first run.
        content_after_first: dict[str, str] = {}
        for r in results1:
            path = vault / r["path"]
            if path.exists():
                content_after_first[r["path"]] = path.read_text(encoding="utf-8")

        # Second apply.
        results2 = objectives.relink(vault, apply=True)
        changed2 = [r for r in results2 if r["changed"]]

        # No file should report changed on second run.
        assert not changed2, (
            f"relink is not idempotent: these files changed on 2nd run: "
            f"{[r['path'] for r in changed2]}"
        )

        # File content must be identical.
        for r in results2:
            path = vault / r["path"]
            if path.exists() and r["path"] in content_after_first:
                current = path.read_text(encoding="utf-8")
                assert current == content_after_first[r["path"]], (
                    f"file content changed on 2nd run: {r['path']}"
                )

    print("PASS test_relink_idempotent")


# ---------------------------------------------------------------------------
# Test (e): plain-id frontmatter fields are UNCHANGED
# ---------------------------------------------------------------------------

def test_relink_plain_id_fields_unchanged() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        objectives.relink(vault, apply=True)

        # topic: related_questions stays as-is.
        topic_fm = _read_fm(vault / "objective/topic/T-0001-test-topic.md")
        assert topic_fm.get("related_questions") == "[Q-0001, Q-0002]", (
            f"topic related_questions changed: {topic_fm.get('related_questions')!r}"
        )

        # research_question: topic field unchanged.
        rq_fm = _read_fm(vault / "objective/research_question/Q-0001-test-rq.md")
        assert rq_fm.get("topic") == "T-0001", (
            f"rq topic field changed: {rq_fm.get('topic')!r}"
        )

        # direction: serves_question unchanged.
        dir_fm = _read_fm(vault / "objective/direction/DIR-0001-test-dir.md")
        assert dir_fm.get("serves_question") == "Q-0001", (
            f"direction serves_question changed: {dir_fm.get('serves_question')!r}"
        )
        # topics field unchanged.
        assert dir_fm.get("topics") == "T-0001, T-0002", (
            f"direction topics field changed: {dir_fm.get('topics')!r}"
        )

        # decision: scope unchanged.
        d_fm = _read_fm(vault / "objective/decision/D-0001-test-decision.md")
        assert d_fm.get("scope") == "all", (
            f"decision scope changed: {d_fm.get('scope')!r}"
        )

        # proposal: from_gap unchanged.
        qp_fm = _read_fm(
            vault / "objective/research_question_proposal/QP-0001-test-prop.md"
        )
        assert "Q-0001" in (qp_fm.get("from_gap") or ""), (
            f"proposal from_gap changed unexpectedly: {qp_fm.get('from_gap')!r}"
        )

    print("PASS test_relink_plain_id_fields_unchanged")


# ---------------------------------------------------------------------------
# Test (f): written_by is set per type (USER vs agent)
# ---------------------------------------------------------------------------

def test_relink_written_by_set() -> None:
    """written_by must be USER for user-authored types and agent name for agent types."""
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        objectives.relink(vault, apply=True)

        # USER types.
        for path, node_id in [
            (vault / "objective/purpose/PURPOSE.md", "purpose"),
            (vault / "objective/topic/T-0001-test-topic.md", "T-0001"),
            (vault / "objective/research_question/Q-0001-test-rq.md", "Q-0001"),
            (vault / "objective/decision/D-0001-test-decision.md", "D-0001"),
        ]:
            fm = _read_fm(path)
            assert fm.get("written_by") == "USER", (
                f"{node_id}: expected written_by=USER, got {fm.get('written_by')!r}"
            )

        # Agent-authored: direction + proposal -> written_by from generated_by.
        dir_fm = _read_fm(vault / "objective/direction/DIR-0001-test-dir.md")
        assert dir_fm.get("written_by") == "research", (
            f"DIR-0001 written_by: expected 'research', got {dir_fm.get('written_by')!r}"
        )
        qp_fm = _read_fm(vault / "objective/research_question_proposal/QP-0001-test-prop.md")
        assert qp_fm.get("written_by") == "research", (
            f"QP-0001 written_by: expected 'research', got {qp_fm.get('written_by')!r}"
        )

    print("PASS test_relink_written_by_set")


# ---------------------------------------------------------------------------
# Test: purpose gets no Links section
# ---------------------------------------------------------------------------

def test_relink_purpose_no_links_section() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        objectives.relink(vault, apply=True)

        purpose_text = (vault / "objective/purpose/PURPOSE.md").read_text(encoding="utf-8")
        assert "<!-- links:auto -->" not in purpose_text, (
            "purpose node must NOT contain a links:auto section"
        )
        assert "## Links" not in purpose_text, (
            "purpose node must NOT contain a ## Links heading"
        )

    print("PASS test_relink_purpose_no_links_section")


# ---------------------------------------------------------------------------
# Test: existing OTHER aliases are preserved, not dropped
# ---------------------------------------------------------------------------

def test_relink_other_aliases_preserved() -> None:
    """Aliases that are NOT the node's own id must survive relink."""
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        obj_init.run_apply(vault)

        # Node with an alias already set to own id + an extra alias.
        _write(vault / "objective/topic/T-0001-pre-aliased.md", """\
---
type: topic
id: T-0001
created: 2026-06-21
updated: 2026-06-21
status: active
aliases: [T-0001, some-other-alias]
related_questions: []
---

## For future Claude
Pre-aliased topic.

# Topic: Pre-aliased
""")

        objectives.relink(vault, apply=True)

        fm = _read_fm(vault / "objective/topic/T-0001-pre-aliased.md")
        aliases = _read_inline_list(fm.get("aliases", ""))
        # Own-id T-0001 must be removed.
        assert "T-0001" not in aliases, (
            f"T-0001 own-id alias should have been removed, aliases={aliases}"
        )
        # Other alias must be preserved.
        assert "some-other-alias" in aliases, (
            f"existing alias 'some-other-alias' was lost: {aliases}"
        )

    print("PASS test_relink_other_aliases_preserved")


# ---------------------------------------------------------------------------
# Test: CLI relink dry-run (no --apply) prints summary, writes nothing
# ---------------------------------------------------------------------------

def test_relink_cli_dryrun() -> None:
    from io import StringIO
    from contextlib import redirect_stdout

    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        buf = StringIO()
        with redirect_stdout(buf):
            rc = objectives.main(["--vault-root", str(vault), "relink"])
        assert rc == 0, f"relink CLI returned non-zero: {rc}"

        output = buf.getvalue()
        assert "DRY-RUN" in output, "dry-run output must say DRY-RUN"
        assert "dry-run: pass --apply" in output, "dry-run hint missing"

        # Files must not have been written (written_by still absent, no links section).
        topic_fm = _read_fm(vault / "objective/topic/T-0001-test-topic.md")
        assert "written_by" not in topic_fm, (
            "dry-run must not write written_by to topic file"
        )

    print("PASS test_relink_cli_dryrun")


# ---------------------------------------------------------------------------
# Test: CLI relink --apply writes files
# ---------------------------------------------------------------------------

def test_relink_cli_apply() -> None:
    from io import StringIO
    from contextlib import redirect_stdout

    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        buf = StringIO()
        with redirect_stdout(buf):
            rc = objectives.main(["--vault-root", str(vault), "relink", "--apply"])
        assert rc == 0, f"relink --apply CLI returned non-zero: {rc}"

        output = buf.getvalue()
        assert "APPLY" in output, "apply output must say APPLY"

        # written_by now present; aliases NOT added.
        topic_fm = _read_fm(vault / "objective/topic/T-0001-test-topic.md")
        assert topic_fm.get("written_by") == "USER", (
            f"after --apply, T-0001 written_by should be USER, got {topic_fm.get('written_by')!r}"
        )
        assert "aliases" not in topic_fm, (
            f"after --apply, aliases must NOT be added to topic, got {topic_fm.get('aliases')!r}"
        )

        # Links section is present and uses full paths.
        topic_body = _read_body(vault / "objective/topic/T-0001-test-topic.md")
        assert "[[objective/purpose/PURPOSE]]" in topic_body, (
            "after --apply, topic links must contain full-path PURPOSE"
        )

    print("PASS test_relink_cli_apply")


# ---------------------------------------------------------------------------
# Test: markers section placement -- after ## For future Claude
# ---------------------------------------------------------------------------

def test_relink_links_placed_after_ffc() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        obj_init.run_apply(vault)

        _write(vault / "objective/topic/T-0001-placement.md", """\
---
type: topic
id: T-0001
created: 2026-06-21
updated: 2026-06-21
status: active
related_questions: [Q-0001]
---

## For future Claude
This is the FFC block. It spans multiple lines.
The links section should come after this block.

# Topic: Placement test

## Summary
Some content here that must not be disrupted.
""")

        objectives.relink(vault, apply=True)

        body = _read_body(vault / "objective/topic/T-0001-placement.md")

        ffc_pos = body.find("## For future Claude")
        links_start_pos = body.find("<!-- links:auto -->")
        summary_pos = body.find("# Topic: Placement test")

        assert ffc_pos != -1, "FFC heading not found"
        assert links_start_pos != -1, "links:auto marker not found"
        assert summary_pos != -1, "Summary heading not found"

        assert ffc_pos < links_start_pos, (
            "links:auto must come AFTER ## For future Claude"
        )
        assert links_start_pos < summary_pos, (
            "links:auto must come BEFORE the main content headings"
        )

    print("PASS test_relink_links_placed_after_ffc")


# ---------------------------------------------------------------------------
# Fixture builder for hot.md tests
# ---------------------------------------------------------------------------

def make_hot_fixture(vault: Path) -> None:
    """Create objective/hot.md plus the node files needed for linkify resolution.

    hot.md body contains:
      - Q-0001 bare  -> should be linkified (node file present)
      - DIR-0001 bare -> should be linkified (node file present)
      - QP-0001 bare  -> should be linkified (node file present)
      - TBD-3         -> must NOT be matched (wrong prefix / digit count)
      - [[objective/research_question/Q-0002-some-title]] -> already wrapped, must stay

    Frontmatter has generated_by: research (no written_by) -> rename expected.
    """
    obj_init.run_apply(vault)

    # Minimal node files so the id->relpath map is populated.
    _write(vault / "objective/research_question/Q-0001-rq-one.md", """\
---
type: research_question
id: Q-0001
created: 2026-06-21
updated: 2026-06-21
solved: "no"
topic: T-0001
priority: high
answer_ref: ""
---

## For future Claude
Test research question one.

# Research question

What is the first test question?
""")

    _write(vault / "objective/direction/DIR-0001-dir-one.md", """\
---
type: direction
id: DIR-0001
created: 2026-06-21
updated: 2026-06-21
generated_by: research
serves_question: Q-0001
topics: T-0001
priority: high
status: open
---

## For future Claude
Test direction one.

## reasoning_pattern
Test.
""")

    _write(vault / "objective/research_question_proposal/QP-0001-prop-one.md", """\
---
type: research_question_proposal
id: QP-0001
created: 2026-06-21
updated: 2026-06-21
generated_by: research
from_gap: gap
status: pending
---

## For future Claude
Test proposal one.
""")

    # Q-0002 node file present (needed to assert already-wrapped link is unchanged).
    _write(vault / "objective/research_question/Q-0002-rq-two.md", """\
---
type: research_question
id: Q-0002
created: 2026-06-21
updated: 2026-06-21
solved: "no"
topic: T-0001
priority: medium
answer_ref: ""
---

## For future Claude
Test research question two.

# Research question

What is the second test question?
""")

    # hot.md itself: bare ids + already-wrapped + TBD-3 token
    _write(vault / "objective/hot.md", """\
---
type: hot
generated_by: research
updated: 2026-06-21
---

# Hot objectives

See Q-0001 for the primary question. DIR-0001 is the leading direction.
QP-0001 is a pending proposal. TBD-3 is not an id. Already wrapped: [[objective/research_question/Q-0002-rq-two]].
""")


# ---------------------------------------------------------------------------
# Test: hot.md prose linkify + frontmatter rename
# ---------------------------------------------------------------------------

def test_relink_hot_md_linkify() -> None:
    """Bare ids in hot.md body become full wikilinks; generated_by -> written_by renamed."""
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_hot_fixture(vault)

        objectives.relink(vault, apply=True)

        hot_path = vault / "objective/hot.md"
        hot_text = hot_path.read_text(encoding="utf-8")
        fm = objectives._parse_fm(hot_text)
        body = objectives._body(hot_text)

        # --- frontmatter assertions ---
        assert fm.get("written_by") == "research", (
            f"hot.md: expected written_by=research after rename, got {fm.get('written_by')!r}"
        )
        assert "generated_by" not in fm, (
            f"hot.md: generated_by should have been removed (renamed), still present: "
            f"{fm.get('generated_by')!r}"
        )

        # --- prose linkify assertions ---
        # Q-0001 bare -> full wikilink
        assert "[[objective/research_question/Q-0001-rq-one]]" in body, (
            f"hot.md: Q-0001 should be linkified to full path, body=\n{body}"
        )
        # Verify no bare Q-0001 remains: split out wikilink tokens and check plain segments.
        _plain_segments = re.sub(r"\[\[[^\]]*\]\]", "", body)
        assert "Q-0001" not in _plain_segments, (
            f"hot.md: bare Q-0001 must not remain in non-wikilink text after linkify, "
            f"plain segments=\n{_plain_segments}"
        )

        # DIR-0001 bare -> full wikilink
        assert "[[objective/direction/DIR-0001-dir-one]]" in body, (
            f"hot.md: DIR-0001 should be linkified, body=\n{body}"
        )

        # QP-0001 bare -> full wikilink
        assert "[[objective/research_question_proposal/QP-0001-prop-one]]" in body, (
            f"hot.md: QP-0001 should be linkified, body=\n{body}"
        )

        # TBD-3 must be untouched (wrong prefix / too few digits)
        assert "TBD-3" in body, (
            f"hot.md: TBD-3 must remain untouched, body=\n{body}"
        )
        assert "[[TBD-3]]" not in body, (
            f"hot.md: TBD-3 must NOT be wrapped in a wikilink, body=\n{body}"
        )

        # Already-wrapped Q-0002 link must not be double-wrapped.
        assert "[[objective/research_question/Q-0002-rq-two]]" in body, (
            f"hot.md: pre-existing [[Q-0002]] wikilink must be preserved, body=\n{body}"
        )
        assert "[[[[" not in body, "hot.md: double-wrapped wikilink detected"
        assert body.count("Q-0002") == 1, (
            f"hot.md: Q-0002 should appear exactly once (pre-wrapped), body=\n{body}"
        )

    print("PASS test_relink_hot_md_linkify")


# ---------------------------------------------------------------------------
# Test: hot.md written_by already present -> no change to frontmatter
# ---------------------------------------------------------------------------

def test_relink_hot_md_written_by_already_present() -> None:
    """If written_by is already in hot.md frontmatter, leave it unchanged."""
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_hot_fixture(vault)

        # Overwrite hot.md with written_by already set.
        _write(vault / "objective/hot.md", """\
---
type: hot
written_by: human
updated: 2026-06-21
---

# Hot objectives

See Q-0001 for the primary question.
""")

        objectives.relink(vault, apply=True)

        fm = objectives._parse_fm(
            (vault / "objective/hot.md").read_text(encoding="utf-8")
        )
        assert fm.get("written_by") == "human", (
            f"hot.md: written_by must not be overwritten, got {fm.get('written_by')!r}"
        )
        assert "generated_by" not in fm, (
            "hot.md: generated_by must not be added when it was absent"
        )

    print("PASS test_relink_hot_md_written_by_already_present")


# ---------------------------------------------------------------------------
# Test: hot.md idempotency -- second run makes no further change
# ---------------------------------------------------------------------------

def test_relink_hot_md_idempotent() -> None:
    """Rerunning relink on hot.md must produce no further changes."""
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_hot_fixture(vault)

        # First apply.
        results1 = objectives.relink(vault, apply=True)
        hot1 = next((r for r in results1 if r["path"] == "objective/hot.md"), None)
        assert hot1 is not None, "hot.md record missing from relink results"
        assert hot1["changed"], "first run should report hot.md changed"

        content_after_first = (vault / "objective/hot.md").read_text(encoding="utf-8")

        # Second apply.
        results2 = objectives.relink(vault, apply=True)
        hot2 = next((r for r in results2 if r["path"] == "objective/hot.md"), None)
        assert hot2 is not None, "hot.md record missing from second relink results"
        assert not hot2["changed"], (
            f"hot.md should not change on second run; got changed=True"
        )

        content_after_second = (vault / "objective/hot.md").read_text(encoding="utf-8")
        assert content_after_first == content_after_second, (
            "hot.md content changed between first and second relink run"
        )

    print("PASS test_relink_hot_md_idempotent")


# ---------------------------------------------------------------------------
# Test: hot.md absent -- relink still works (no crash)
# ---------------------------------------------------------------------------

def test_relink_hot_md_absent() -> None:
    """relink must not crash when objective/hot.md does not exist."""
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        obj_init.run_apply(vault)

        # obj_init creates hot.md -- remove it to simulate the absent case.
        hot_path = vault / "objective" / "hot.md"
        if hot_path.exists():
            hot_path.unlink()

        results = objectives.relink(vault, apply=True)
        hot_record = next((r for r in results if r.get("path") == "objective/hot.md"), None)
        assert hot_record is None, (
            "relink should not return a record for missing hot.md"
        )

    print("PASS test_relink_hot_md_absent")


# ---------------------------------------------------------------------------
# Test: hot.md dry-run does not write the file
# ---------------------------------------------------------------------------

def test_relink_hot_md_dryrun_no_write() -> None:
    """hot.md must not be written when apply=False."""
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_hot_fixture(vault)

        mtime_before = (vault / "objective/hot.md").stat().st_mtime

        results = objectives.relink(vault, apply=False)
        hot_record = next((r for r in results if r["path"] == "objective/hot.md"), None)
        assert hot_record is not None, "dry-run should still report hot.md record"
        assert hot_record["changed"], "dry-run should report hot.md would change"

        mtime_after = (vault / "objective/hot.md").stat().st_mtime
        assert mtime_before == mtime_after, "dry-run must not write hot.md"

    print("PASS test_relink_hot_md_dryrun_no_write")


# ---------------------------------------------------------------------------
# Self-running fallback
# ---------------------------------------------------------------------------

def _run_all() -> int:
    test_relink_dryrun_no_writes()
    test_relink_no_aliases_added()
    test_relink_own_id_alias_removed()
    test_relink_generated_by_removal()
    test_relink_written_by_per_type()
    test_relink_written_by_agent_todo_default()
    test_relink_links_section_full_paths()
    test_relink_idempotent()
    test_relink_plain_id_fields_unchanged()
    test_relink_written_by_set()
    test_relink_purpose_no_links_section()
    test_relink_other_aliases_preserved()
    test_relink_cli_dryrun()
    test_relink_cli_apply()
    test_relink_links_placed_after_ffc()
    test_relink_hot_md_linkify()
    test_relink_hot_md_written_by_already_present()
    test_relink_hot_md_idempotent()
    test_relink_hot_md_absent()
    test_relink_hot_md_dryrun_no_write()
    print("\nAll relink tests PASSED.")
    return 0


if __name__ == "__main__":
    raise SystemExit(_run_all())
