#!/usr/bin/env python3
"""Hermetic tests for the `relink` verb in agents/objectives.py.

No network, no live vault. Builds a temp fixture with one of each node type,
runs relink --apply, and asserts correctness.

Run: .venv/bin/python -m pytest tests/test_objectives_relink.py -q
"""

from __future__ import annotations

import importlib.util
import os
import re
import sys
import tempfile
from pathlib import Path

REPO = Path(os.environ.get("CODE_PATH", "/home/jpietrak/second_brain"))
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))


def _load(modname: str, relpath: str):
    spec = importlib.util.spec_from_file_location(modname, REPO / relpath)
    mod = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(mod)
    return mod


objectives = _load("objectives", "agents/objectives.py")
obj_init = _load("obj_init", "scripts/obj_init.py")


# ---------------------------------------------------------------------------
# Fixture builders
# ---------------------------------------------------------------------------

def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def make_relink_fixture(vault: Path) -> None:
    """Create one node of each relevant type for relink testing.

    Uses plain-id frontmatter fields exactly as the live vault does.
    Does NOT pre-populate aliases or written_by (relink must add them).
    """
    obj_init.run_apply(vault)

    # -- purpose --
    _write(vault / "objective/purpose/PURPOSE.md", """\
---
type: purpose
id: purpose
created: 2026-06-21
updated: 2026-06-21
status: active
vault: TestVault
---

## For future Claude
This is the vault PURPOSE file.

# Vault purpose

## Mission
Test vault for relink tests.
""")

    # -- topic -- related_questions as inline YAML list
    _write(vault / "objective/topic/T-0001-test-topic.md", """\
---
type: topic
id: T-0001
created: 2026-06-21
updated: 2026-06-21
status: active
related_questions: [Q-0001, Q-0002]
---

## For future Claude
This is a TOPIC node.

# Topic: Test topic

## Summary
A test topic node.
""")

    # -- research_question -- primary topic + secondary topic in body preamble
    _write(vault / "objective/research_question/Q-0001-test-rq.md", """\
---
type: research_question
id: Q-0001
created: 2026-06-21
updated: 2026-06-21
solved: "no"
topic: T-0001
priority: high
answer_ref: ""
---

## For future Claude
This is a RESEARCH QUESTION node.
Secondary topic: T-0002 (optical accelerators).

# Research question

What is the test latency floor?
""")

    # -- direction -- topics as comma-separated string (live vault format)
    _write(vault / "objective/direction/DIR-0001-test-dir.md", """\
---
type: direction
id: DIR-0001
created: 2026-06-22
updated: 2026-06-22
generated_by: research
serves_question: Q-0001
topics: T-0001, T-0002
targets_gap: "test gap"
priority: high
status: open
---

## For future Claude
This direction was generated by obj-synth.

## reasoning_pattern
Test reasoning.

## expected_evidence
Test evidence.

## seed_queries
Test queries.

## solves_when
Test condition.
""")

    # -- research_question_proposal -- from_gap contains Q and T ids
    _write(vault / "objective/research_question_proposal/QP-0001-test-prop.md", """\
---
type: research_question_proposal
id: QP-0001
created: 2026-06-22
updated: 2026-06-22
generated_by: research
from_gap: Cross-cutting gap involving Q-0001 and Q-0002; also relevant to T-0003
status: pending
---

## For future Claude
This proposal was generated by obj-synth.

## Proposed question
What test question should we ask?

## Rationale
Related to Q-0001 and T-0001 work in the vault.
""")

    # -- decision -- scope=all -> links PURPOSE
    _write(vault / "objective/decision/D-0001-test-decision.md", """\
---
type: decision
id: D-0001
created: 2026-06-21
updated: 2026-06-21
status: active
scope: all
---

## For future Claude
This is a DECISION node.

# Decision

Do not fetch web content.
""")

    # -- decision with node-id scope -- scope=Q-0001
    _write(vault / "objective/decision/D-0002-scoped-decision.md", """\
---
type: decision
id: D-0002
created: 2026-06-21
updated: 2026-06-21
status: active
scope: Q-0001
---

## For future Claude
This decision governs Q-0001 specifically.

# Decision

Scoped decision content.
""")


# ---------------------------------------------------------------------------
# Helper: read frontmatter + body
# ---------------------------------------------------------------------------

_FM_RE = re.compile(r"^---\n(.*?)\n---(?:\n|$)", re.DOTALL)


def _read_fm(path: Path) -> dict[str, str]:
    return objectives._parse_fm(path.read_text(encoding="utf-8"))


def _read_body(path: Path) -> str:
    return objectives._body(path.read_text(encoding="utf-8"))


def _read_inline_list(raw: str) -> list[str]:
    return objectives._parse_inline_list(raw)


# ---------------------------------------------------------------------------
# Test: dry-run reports changes without writing
# ---------------------------------------------------------------------------

def test_relink_dryrun_no_writes() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        # Capture mtimes before.
        topic_path = vault / "objective/topic/T-0001-test-topic.md"
        mtime_before = topic_path.stat().st_mtime

        results = objectives.relink(vault, apply=False)
        assert results, "relink returned empty results"

        # File must NOT be written in dry-run.
        mtime_after = topic_path.stat().st_mtime
        assert mtime_before == mtime_after, "dry-run must not write files"

        # But results should show changes planned.
        topic_result = next(
            (r for r in results if "T-0001" in r["path"]), None
        )
        assert topic_result is not None, "no result for T-0001"
        assert topic_result["changed"], "T-0001 should report planned change"

    print("PASS test_relink_dryrun_no_writes")


# ---------------------------------------------------------------------------
# Test (a): aliases contain the node id after apply
# ---------------------------------------------------------------------------

def test_relink_aliases_contain_id() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        objectives.relink(vault, apply=True)

        # purpose -> aliases: [purpose]
        purpose_fm = _read_fm(vault / "objective/purpose/PURPOSE.md")
        aliases = _read_inline_list(purpose_fm.get("aliases", ""))
        assert "purpose" in aliases, f"purpose aliases: {aliases}"

        # topic -> aliases: [T-0001]
        topic_fm = _read_fm(vault / "objective/topic/T-0001-test-topic.md")
        aliases = _read_inline_list(topic_fm.get("aliases", ""))
        assert "T-0001" in aliases, f"T-0001 aliases: {aliases}"

        # research_question -> aliases: [Q-0001]
        rq_fm = _read_fm(vault / "objective/research_question/Q-0001-test-rq.md")
        aliases = _read_inline_list(rq_fm.get("aliases", ""))
        assert "Q-0001" in aliases, f"Q-0001 aliases: {aliases}"

        # direction -> aliases: [DIR-0001]
        dir_fm = _read_fm(vault / "objective/direction/DIR-0001-test-dir.md")
        aliases = _read_inline_list(dir_fm.get("aliases", ""))
        assert "DIR-0001" in aliases, f"DIR-0001 aliases: {aliases}"

        # proposal -> aliases: [QP-0001]
        qp_fm = _read_fm(vault / "objective/research_question_proposal/QP-0001-test-prop.md")
        aliases = _read_inline_list(qp_fm.get("aliases", ""))
        assert "QP-0001" in aliases, f"QP-0001 aliases: {aliases}"

        # decision -> aliases: [D-0001]
        d_fm = _read_fm(vault / "objective/decision/D-0001-test-decision.md")
        aliases = _read_inline_list(d_fm.get("aliases", ""))
        assert "D-0001" in aliases, f"D-0001 aliases: {aliases}"

    print("PASS test_relink_aliases_contain_id")


# ---------------------------------------------------------------------------
# Test (b): written_by set correctly per type; generated_by preserved
# ---------------------------------------------------------------------------

def test_relink_written_by_per_type() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        objectives.relink(vault, apply=True)

        # USER types.
        for path, node_id in [
            (vault / "objective/purpose/PURPOSE.md", "purpose"),
            (vault / "objective/topic/T-0001-test-topic.md", "T-0001"),
            (vault / "objective/research_question/Q-0001-test-rq.md", "Q-0001"),
            (vault / "objective/decision/D-0001-test-decision.md", "D-0001"),
        ]:
            fm = _read_fm(path)
            assert fm.get("written_by") == "USER", (
                f"{node_id}: expected written_by=USER, got {fm.get('written_by')!r}"
            )

        # Agent-authored types: direction has generated_by=research -> written_by=research.
        dir_fm = _read_fm(vault / "objective/direction/DIR-0001-test-dir.md")
        assert dir_fm.get("written_by") == "research", (
            f"DIR-0001 written_by: expected 'research', got {dir_fm.get('written_by')!r}"
        )
        # generated_by must be KEPT (not removed) -- compatibility with scan_objectives.
        assert dir_fm.get("generated_by") == "research", (
            f"DIR-0001 generated_by must be preserved, got {dir_fm.get('generated_by')!r}"
        )

        # Proposal has generated_by=research -> written_by=research.
        qp_fm = _read_fm(vault / "objective/research_question_proposal/QP-0001-test-prop.md")
        assert qp_fm.get("written_by") == "research", (
            f"QP-0001 written_by: expected 'research', got {qp_fm.get('written_by')!r}"
        )
        assert qp_fm.get("generated_by") == "research", (
            "QP-0001 generated_by must be preserved"
        )

    print("PASS test_relink_written_by_per_type")


# ---------------------------------------------------------------------------
# Test (b2): agent_todo with no generated_by gets written_by=research
# ---------------------------------------------------------------------------

def test_relink_written_by_agent_todo_default() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        obj_init.run_apply(vault)

        _write(vault / "objective/agent_todo/TODO-0001-test.md", """\
---
type: agent_todo
id: TODO-0001
created: 2026-06-22
updated: 2026-06-22
status: open
---

## For future Claude
Test todo.

# Todo

Do something.
""")

        objectives.relink(vault, apply=True)

        todo_fm = _read_fm(vault / "objective/agent_todo/TODO-0001-test.md")
        assert todo_fm.get("written_by") == "research", (
            f"TODO-0001 without generated_by should default to 'research', "
            f"got {todo_fm.get('written_by')!r}"
        )

    print("PASS test_relink_written_by_agent_todo_default")


# ---------------------------------------------------------------------------
# Test (c): ## Links section contains expected wikilinks per type
# ---------------------------------------------------------------------------

def test_relink_links_section_content() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        objectives.relink(vault, apply=True)

        # purpose: NO ## Links section.
        purpose_body = _read_body(vault / "objective/purpose/PURPOSE.md")
        assert "<!-- links:auto -->" not in purpose_body, (
            "purpose must NOT get a Links section"
        )

        # topic: part of PURPOSE + question links.
        topic_body = _read_body(vault / "objective/topic/T-0001-test-topic.md")
        assert "[[PURPOSE]]" in topic_body, "topic: missing [[PURPOSE]] link"
        assert "[[Q-0001]]" in topic_body, "topic: missing [[Q-0001]] link"
        assert "[[Q-0002]]" in topic_body, "topic: missing [[Q-0002]] link"

        # research_question: primary topic + secondary topic.
        rq_body = _read_body(vault / "objective/research_question/Q-0001-test-rq.md")
        assert "[[T-0001]]" in rq_body, "rq: missing primary topic [[T-0001]]"
        assert "[[T-0002]]" in rq_body, "rq: missing secondary topic [[T-0002]]"

        # direction: serves Q-0001, topics T-0001 + T-0002.
        dir_body = _read_body(vault / "objective/direction/DIR-0001-test-dir.md")
        assert "[[Q-0001]]" in dir_body, "direction: missing [[Q-0001]] serves link"
        assert "[[T-0001]]" in dir_body, "direction: missing [[T-0001]] topic link"
        assert "[[T-0002]]" in dir_body, "direction: missing [[T-0002]] topic link"
        assert "- serves:" in dir_body, "direction: missing 'serves' relation label"
        assert "- topic:" in dir_body, "direction: missing 'topic' relation label"

        # research_question_proposal: Q-0001, Q-0002, T-0003 from from_gap; T-0001 from body.
        qp_body = _read_body(vault / "objective/research_question_proposal/QP-0001-test-prop.md")
        assert "[[Q-0001]]" in qp_body, "QP-0001: missing [[Q-0001]]"
        assert "[[Q-0002]]" in qp_body, "QP-0001: missing [[Q-0002]]"
        assert "[[T-0003]]" in qp_body, "QP-0001: missing [[T-0003]] from from_gap"
        assert "[[T-0001]]" in qp_body, "QP-0001: missing [[T-0001]] from body"

        # decision scope=all -> governs PURPOSE.
        d_body = _read_body(vault / "objective/decision/D-0001-test-decision.md")
        assert "[[PURPOSE]]" in d_body, "D-0001: missing [[PURPOSE]] governs link"
        assert "- governs:" in d_body, "D-0001: missing 'governs' relation"

        # decision scope=Q-0001 -> governs Q-0001.
        d2_body = _read_body(vault / "objective/decision/D-0002-scoped-decision.md")
        assert "[[Q-0001]]" in d2_body, "D-0002: missing [[Q-0001]] governs link"
        assert "[[PURPOSE]]" not in d2_body, (
            "D-0002 scope=Q-0001 must NOT link PURPOSE"
        )

    print("PASS test_relink_links_section_content")


# ---------------------------------------------------------------------------
# Test (d): plain-id frontmatter fields are UNCHANGED
# ---------------------------------------------------------------------------

def test_relink_plain_id_fields_unchanged() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        objectives.relink(vault, apply=True)

        # topic: related_questions stays as-is.
        topic_fm = _read_fm(vault / "objective/topic/T-0001-test-topic.md")
        assert topic_fm.get("related_questions") == "[Q-0001, Q-0002]", (
            f"topic related_questions changed: {topic_fm.get('related_questions')!r}"
        )

        # research_question: topic field unchanged.
        rq_fm = _read_fm(vault / "objective/research_question/Q-0001-test-rq.md")
        assert rq_fm.get("topic") == "T-0001", (
            f"rq topic field changed: {rq_fm.get('topic')!r}"
        )

        # direction: serves_question unchanged.
        dir_fm = _read_fm(vault / "objective/direction/DIR-0001-test-dir.md")
        assert dir_fm.get("serves_question") == "Q-0001", (
            f"direction serves_question changed: {dir_fm.get('serves_question')!r}"
        )
        # topics field unchanged.
        assert dir_fm.get("topics") == "T-0001, T-0002", (
            f"direction topics field changed: {dir_fm.get('topics')!r}"
        )

        # decision: scope unchanged.
        d_fm = _read_fm(vault / "objective/decision/D-0001-test-decision.md")
        assert d_fm.get("scope") == "all", (
            f"decision scope changed: {d_fm.get('scope')!r}"
        )

        # proposal: from_gap unchanged.
        qp_fm = _read_fm(
            vault / "objective/research_question_proposal/QP-0001-test-prop.md"
        )
        assert "Q-0001" in (qp_fm.get("from_gap") or ""), (
            f"proposal from_gap changed unexpectedly: {qp_fm.get('from_gap')!r}"
        )

    print("PASS test_relink_plain_id_fields_unchanged")


# ---------------------------------------------------------------------------
# Test (e): idempotency -- second run writes nothing
# ---------------------------------------------------------------------------

def test_relink_idempotent() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        # First apply.
        results1 = objectives.relink(vault, apply=True)
        changed1 = [r for r in results1 if r["changed"]]
        assert changed1, "first relink should change at least some files"

        # Snapshot content after first run.
        content_after_first: dict[str, str] = {}
        for r in results1:
            path = vault / r["path"]
            if path.exists():
                content_after_first[r["path"]] = path.read_text(encoding="utf-8")

        # Second apply.
        results2 = objectives.relink(vault, apply=True)
        changed2 = [r for r in results2 if r["changed"]]

        # No file should report changed on second run.
        assert not changed2, (
            f"relink is not idempotent: these files changed on 2nd run: "
            f"{[r['path'] for r in changed2]}"
        )

        # File content must be identical.
        for r in results2:
            path = vault / r["path"]
            if path.exists() and r["path"] in content_after_first:
                current = path.read_text(encoding="utf-8")
                assert current == content_after_first[r["path"]], (
                    f"file content changed on 2nd run: {r['path']}"
                )

    print("PASS test_relink_idempotent")


# ---------------------------------------------------------------------------
# Test (f): purpose gets no Links section
# ---------------------------------------------------------------------------

def test_relink_purpose_no_links_section() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        objectives.relink(vault, apply=True)

        purpose_text = (vault / "objective/purpose/PURPOSE.md").read_text(encoding="utf-8")
        assert "<!-- links:auto -->" not in purpose_text, (
            "purpose node must NOT contain a links:auto section"
        )
        assert "## Links" not in purpose_text, (
            "purpose node must NOT contain a ## Links heading"
        )

    print("PASS test_relink_purpose_no_links_section")


# ---------------------------------------------------------------------------
# Test: existing aliases are merged, not duplicated
# ---------------------------------------------------------------------------

def test_relink_aliases_no_duplicate() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        obj_init.run_apply(vault)

        # Node with an alias already set.
        _write(vault / "objective/topic/T-0001-pre-aliased.md", """\
---
type: topic
id: T-0001
created: 2026-06-21
updated: 2026-06-21
status: active
aliases: [T-0001, some-other-alias]
related_questions: []
---

## For future Claude
Pre-aliased topic.

# Topic: Pre-aliased
""")

        objectives.relink(vault, apply=True)

        fm = _read_fm(vault / "objective/topic/T-0001-pre-aliased.md")
        aliases = _read_inline_list(fm.get("aliases", ""))
        assert aliases.count("T-0001") == 1, (
            f"T-0001 alias duplicated: {aliases}"
        )
        # The other existing alias must be preserved.
        assert "some-other-alias" in aliases, (
            f"existing alias 'some-other-alias' was lost: {aliases}"
        )

    print("PASS test_relink_aliases_no_duplicate")


# ---------------------------------------------------------------------------
# Test: CLI relink dry-run (no --apply) prints summary, writes nothing
# ---------------------------------------------------------------------------

def test_relink_cli_dryrun() -> None:
    from io import StringIO
    from contextlib import redirect_stdout

    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        buf = StringIO()
        with redirect_stdout(buf):
            rc = objectives.main(["--vault-root", str(vault), "relink"])
        assert rc == 0, f"relink CLI returned non-zero: {rc}"

        output = buf.getvalue()
        assert "DRY-RUN" in output, "dry-run output must say DRY-RUN"
        assert "dry-run: pass --apply" in output, "dry-run hint missing"

        # Files must not have been written (aliases still absent).
        topic_fm = _read_fm(vault / "objective/topic/T-0001-test-topic.md")
        assert "aliases" not in topic_fm, (
            "dry-run must not write aliases to topic file"
        )

    print("PASS test_relink_cli_dryrun")


# ---------------------------------------------------------------------------
# Test: CLI relink --apply writes files
# ---------------------------------------------------------------------------

def test_relink_cli_apply() -> None:
    from io import StringIO
    from contextlib import redirect_stdout

    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        make_relink_fixture(vault)

        buf = StringIO()
        with redirect_stdout(buf):
            rc = objectives.main(["--vault-root", str(vault), "relink", "--apply"])
        assert rc == 0, f"relink --apply CLI returned non-zero: {rc}"

        output = buf.getvalue()
        assert "APPLY" in output, "apply output must say APPLY"

        # Aliases now present.
        topic_fm = _read_fm(vault / "objective/topic/T-0001-test-topic.md")
        aliases = _read_inline_list(topic_fm.get("aliases", ""))
        assert "T-0001" in aliases, f"after --apply, T-0001 alias missing: {aliases}"

    print("PASS test_relink_cli_apply")


# ---------------------------------------------------------------------------
# Test: markers section placement -- after ## For future Claude
# ---------------------------------------------------------------------------

def test_relink_links_placed_after_ffc() -> None:
    with tempfile.TemporaryDirectory() as td:
        vault = Path(td) / "vault"
        vault.mkdir()
        obj_init.run_apply(vault)

        _write(vault / "objective/topic/T-0001-placement.md", """\
---
type: topic
id: T-0001
created: 2026-06-21
updated: 2026-06-21
status: active
related_questions: [Q-0001]
---

## For future Claude
This is the FFC block. It spans multiple lines.
The links section should come after this block.

# Topic: Placement test

## Summary
Some content here that must not be disrupted.
""")

        objectives.relink(vault, apply=True)

        body = _read_body(vault / "objective/topic/T-0001-placement.md")

        ffc_pos = body.find("## For future Claude")
        links_start_pos = body.find("<!-- links:auto -->")
        summary_pos = body.find("# Topic: Placement test")

        assert ffc_pos != -1, "FFC heading not found"
        assert links_start_pos != -1, "links:auto marker not found"
        assert summary_pos != -1, "Summary heading not found"

        assert ffc_pos < links_start_pos, (
            "links:auto must come AFTER ## For future Claude"
        )
        assert links_start_pos < summary_pos, (
            "links:auto must come BEFORE the main content headings"
        )

    print("PASS test_relink_links_placed_after_ffc")


# ---------------------------------------------------------------------------
# Self-running fallback
# ---------------------------------------------------------------------------

def _run_all() -> int:
    test_relink_dryrun_no_writes()
    test_relink_aliases_contain_id()
    test_relink_written_by_per_type()
    test_relink_written_by_agent_todo_default()
    test_relink_links_section_content()
    test_relink_plain_id_fields_unchanged()
    test_relink_idempotent()
    test_relink_purpose_no_links_section()
    test_relink_aliases_no_duplicate()
    test_relink_cli_dryrun()
    test_relink_cli_apply()
    test_relink_links_placed_after_ffc()
    print("\nAll relink tests PASSED.")
    return 0


if __name__ == "__main__":
    raise SystemExit(_run_all())
